### ISSUE TITLE
Rails 6.1.0rc2 - undefined method `construct_tables!'

### ISSUE THREAD

**Issue by JasonBarnabe** [pat/joiner#8]
Testing my Rails app on 6.1.0 - https://github.com/JasonBarnabe/greasyfork/pull/830, I get an error:

```
/home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/joiner-0.5.0/lib/joiner/join_dependency.rb:4:in `join_association_for': undefined method `construct_tables!' for #<Joiner::JoinDependency:0x0000557930d4f590> (NoMethodError)
```

Fullish trace:

```
	32: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/test.rb:10:in `start'
	31: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/configuration.rb:119:in `render_to_file'
	30: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/2.6.0/open-uri.rb:37:in `open'
	29: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/2.6.0/open-uri.rb:37:in `open'
	28: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/configuration.rb:119:in `block in render_to_file'
	27: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/configuration.rb:111:in `render'
	26: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/riddle-2.4.2/lib/riddle/configuration.rb:45:in `render'
	25: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/riddle-2.4.2/lib/riddle/configuration.rb:45:in `collect'
	24: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/riddle-2.4.2/lib/riddle/configuration.rb:45:in `block in render'
	23: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/core/index.rb:74:in `render'
	22: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/riddle-2.4.2/lib/riddle/configuration/index.rb:30:in `render'
	21: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/riddle-2.4.2/lib/riddle/configuration/index.rb:30:in `collect'
	20: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/riddle-2.4.2/lib/riddle/configuration/index.rb:30:in `block in render'
	19: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/sql_source.rb:83:in `render'
	18: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/sql_source.rb:165:in `prepare_for_render'
	17: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/sql_source.rb:140:in `build_sql_query'
	16: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/sql_builder.rb:13:in `sql_query'
	15: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/sql_builder/statement.rb:14:in `to_relation'
	14: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/sql_builder/statement.rb:49:in `filter_by_scopes'
	13: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/sql_builder/statement.rb:84:in `scope_by_select'
	12: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/sql_builder/statement.rb:117:in `select_clause'
	11: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/sql_builder/statement.rb:70:in `presenters_to_select'
	10: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/sql_builder/statement.rb:70:in `collect'
	 9: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/property_sql_presenter.rb:19:in `to_select'
	 8: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/property_sql_presenter.rb:43:in `casted_column_with_table'
	 7: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/property_sql_presenter.rb:62:in `columns_with_table'
	 6: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/property_sql_presenter.rb:62:in `collect'
	 5: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/column_sql_presenter.rb:18:in `with_table'
	 4: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/column_sql_presenter.rb:34:in `escape_table?'
	 3: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/thinking-sphinx-7d3bcdbf8508/lib/thinking_sphinx/active_record/column_sql_presenter.rb:48:in `table'
	 2: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/joiner-0.5.0/lib/joiner/joins.rb:24:in `alias_for'
	 1: from /home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/joiner-0.5.0/lib/joiner/joins.rb:44:in `association_for'
/home/jason/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/joiner-0.5.0/lib/joiner/join_dependency.rb:4:in `join_association_for': undefined method `construct_tables!' for #<Joiner::JoinDependency:0x0000557930d4f590> (NoMethodError)
```

Looks like it was removed - https://github.com/rails/rails/commit/590b045ee2c0906ff162e6658a184afb201865d7#diff-06059df8d3dee3101718fb2c01151ad0

**Comment by pat** [comment]
Thanks for reporting this! I'll try to get to it soon - I'm moving house this coming week though, so no promises it'll happen in the next few days 😅

**Comment by pat** [comment]
Okay, got a fix published - v0.6.0 works with Rails 6.1.
